---
title: "Machine Learning project"
author: "Karen Brenchley"
date: "January 17, 2015"
output: html_document
---
Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. 

In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 

Six young health participants were asked to perform one set of 10 repetitions of the Unilateral Dumbbell Biceps Curl in five different fashions: exactly according to the specification (Class A), throwing the elbows to the front (Class B), lifting the dumbbell only halfway (Class C), lowering the dumbbell only halfway (Class D) and throwing the hips to the front (Class E).

Goal:

The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. You may use any of the other variables to predict with.


## How I built my model




## How I used cross validation

1. Use the training set

2. Split it into training/test sets

K-fold
10 training/testing sets
17660 per set

3. Build a model on the training set

4. Evaluate on the test set

5. Repeat and average the estimated errors

## What I think the expected out of sample error is

For continuous data: Root mean squared error (RMSE):
sqrt((sum(pred - truth)^2)/n)

Categorical data: accuracy -- fraction correct
use results from second half of project to project this
-- or Kappa -- see 

From Quiz 3.4:
missClass = function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}

## Why I made the choices I made

```{r}
setwd("~/Documents/Coursera/Practical Machine Learning/Project/Practical-Machine-Learning")

download.file(url="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", destfile="pml-training.csv",method="curl")
download.file(url="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv",destfil="pml-testing.csv",method = "curl")

training <- read.csv("pml-training.csv")
testing <- read.csv("pml-testing.csv")

library(caret)
library(randomForest)
library(tree)
set.seed(11854)

## Cross Validation: Make training/testing sets out of training set

train.folds <- createFolds(y = training$classe, k=10, list=TRUE, returnTrain=TRUE)
test.folds <- createFolds(y = training$classe, k=10, list=TRUE, returnTrain=FALSE)
sapply(train.folds, length)
sapply(test.folds, length)

train.set1 <- train.folds[[1]]
train1 <- training[train.set1,]
test.set1 <- test.folds[[1]]
test1 <- training[test.set1,]



## -------- Creating models ---------

## all in

fit.all <- train(classe ~ ., data = training, method ="glm")
fit.all <- train(classe ~ ., data = train1, method = "glm")

train(x,y, , method = "glm", metric = "Accuracy")

## some data mostly NA, so let's remove zero covariates

near.zero <- nearZeroVar(training,saveMetrics = TRUE)
training.new <- training[,near.zero$nzv == FALSE]

## and get rid of the ones that are mostly NA

training.new <- training.new[colSums(is.na(training.new)) == 0]

## make new training sets based on training.new

train.folds <- createFolds(y = training.new$classe, k=10, list=TRUE, returnTrain=TRUE)
test.folds <- createFolds(y = training.new$classe, k=10, list=TRUE, returnTrain=FALSE)
sapply(train.folds, length)
sapply(test.folds, length)

train.set1 <- train.folds[[1]]
train1 <- training.new[train.set1,]
test.set1 <- test.folds[[1]]
test1 <- training[test.set1,]

train.set2 <- train.folds[[2]]
train2 <- training.new[train.set2,]
test.set2 <- test.folds[[2]]
test2 <- training[test.set2,]

## fix K-fold testing set so it can be predicted on
len <- length(test1$classe)
test1$classe <- NULL
test1$problem_id <- 1:len

len <- length(test2$classe)
test2$classe <- NULL
test2$problem_id <- 1:len

## belt, forearm, arm, dumbbell

## ===============================================
## correlated predictors and principal compoenents

## converting factors, char variables to numbers
train1$cvtd_timestamp <-  as.numeric(train1$cvtd_timestamp)
train1$user_name <- as.numeric(train1$user_name)
test1$cvtd_timestamp <-  as.numeric(test1$cvtd_timestamp)
test1$user_name <- as.numeric(test1$user_name)

train2$cvtd_timestamp <-  as.numeric(train2$cvtd_timestamp)
train2$user_name <- as.numeric(train2$user_name)
test2$cvtd_timestamp <-  as.numeric(test2$cvtd_timestamp)
test2$user_name <- as.numeric(test2$user_name)

## Finding the variables that have useful variation
M <- abs(cor(train1[,-59]))
diag(M) <- 0
cor.pred <- which(M > 0.8, arr.ind=T)

train1.small <- train1[,c(2,5,7,8,9,10,14,15,16,17,24,25,27,30,31,32,34,35,37,39,40,42,51,52)]
train1.small$classe <- train1$classe

## now with > 90%
cor.pred.90 <- which(M > 0.9, arr.ind=T)

train1.smaller <- train1[,c(7,8,10,14,15,16,24,25,37,39,52)]
train1.smaller$classe <- train1$classe

## ===========================================================
## Try models using the new training sets

## ---rpart----
fitRpart.small <- train(classe ~ ., data = train1.small, method="rpart")
fitRpart.smaller <- train(classe ~ ., data = train1.smaller, method="rpart")

print(fitRpart.small$finalModel)
plot(fitRpart.small$finalModel, uniform=TRUE, main="rpart Tree with small data")
text(fitRpart.small$finalModel, use.n=TRUE, all=TRUE, cex=.8)

print(fitRpart.smaller$finalModel)
plot(fitRpart.smaller$finalModel, uniform=TRUE, main="rpart Tree with smaller data")
text(fitRpart.smaller$finalModel, use.n=TRUE, all=TRUE, cex=.8)

predictionRpart.small <- predict(fitRpart.small,test1)
predictionRpart.smaller <- predict(fitRpart.smaller,test1)

## Test prediction accuracy
temp <- training[test.set1,]

resultsRpart.small <- data.frame(predictionRpart.small, temp$classe)
accuracyRpart.small <- sum(resultsRpart.small[,1] == 
                                 resultsRpart.small[,2])/length(temp$classe)
accuracyRpart.small
## [1] 0.5165563

resultsRpart.smaller <- data.frame(predictionRpart.smaller, temp$classe)
accuracyRpart.smaller <- sum(resultsRpart.smaller[,1] == 
                                 resultsRpart.smaller[,2])/length(temp$classe)
accuracyRpart.smaller
## [1] 0.4228222

## ----Tree----
fitTree.small <- tree(classe ~ ., data = train1.small)
fitTree.smaller <- tree(classe ~ ., data = train1.smaller)

fitTree.small
plot(fitTree.small)
text(fitTree.small)

predictionTree.small <- predict(fitTree.small, test1)
predictionTree.smaller <- predict(fitTree.smaller, test1)

## look at variable importance
round(importance(predictionTree.small), 2)
round(importance(predictionTree.smaller), 2)

## Test prediction accuracy
temp <- training[test.set1,]

resultsTree.small <- data.frame(predictionTree.small, temp$classe)
accTree.small <- sum(resultsTree.small[,1] == resultsTree.small[,2])/length(temp$classe)
accTree.small
## [1] 0.1742231

resultsTree.smaller <- data.frame(predictionTree.smaller, temp$classe)
accTree.smaller <- sum(resultsTree.smaller[,1] == resultsTree.smaller[,2])/length(temp$classe)
accTree.smaller
## [1] 0.03158431

## ----Random Forests----

## with train
fitTrainRf.small <- train(classe ~ ., data = train1.small, method="rf", prox=TRUE)
fitTrainRf.smaller <- train(classe ~ ., data = train1.smaller, method="rf", prox=TRUE)

getTree(fitTrainRf.small$finalModel, k=2)
getTree(fitTrainRf.smaller$finalModel, k=2)

predictionTrainRf.small <- predict(fitTrainRf.small, test1)
predictionTrainRf.smaller <- predict(fitTrainRf.smaller, test1)

## Test prediction accuracy
temp <- training[test.set1,]

resultsTrainRf.small <- data.frame(predictionTrainRf.small, temp$classe)
accTrainRf.small <- sum(resultsTrainRf.small[,1] == 
                            resultsTrainRf.small[,2])/length(temp$classe)
accTrainRf.small

resultsTrainRf.smaller <- data.frame(predictionTrainRf.smaller, temp$classe)
accTrainRf.smaller <- sum(resultsTrainRf.small[,1] == 
                            resultsTrainRf.small[,2])/length(temp$classe)
accTrainRf.smaller

## with RandomForest

fitRf.small <- randomForest(classe ~ ., data = train1.small, importance=TRUE, proximity = TRUE)
fitRf.smaller <- randomForest(classe ~ ., data = train1.smaller, importance=TRUE, proximity = TRUE)

predictionRf.small <- predict(fitRf.small, test1)
predictionRf.smaller <- predict(fitRf.smaller, test1)

## Test prediction accuracy
temp <- training[test.set1,]

resultsRf.small <- data.frame(predictionRf.small, temp$classe)
accRf.small <-sum(resultsRf.small[,1] == resultsRf.small[,2])/length(temp$classe)
accRf.small
## [1] 0.9989801

resultsRf.smaller <- data.frame(predictionRf.smaller, temp$classe)
accRf.smaller <-sum(resultsRf.smaller[,1] == resultsRf.smaller[,2])/length(temp$classe)
accRf.smaller
## [1] 0.9928608

## ----Boosting ----
## Using gbm (boosting with trees)

fitBoost.small <- train(classe ~ ., data = train1.small, method="gbm", verbose=FALSE)
fitBoost.smaller <- train(classe ~ ., data = train1.smaller, method="gbm", verbose=FALSE)

predictionBoost.small <- predict(fitBoost.small, test1)
predictionBoost.smaller <- predict(fitBoost.smaller, test1)

qplot(predictionBoost.small, classe, data = train1.small)
qplot(predictionBoost.smaller, classe, data = train1.smaller)

## Test prediction accuracy
temp <- training[test.set1,]

resultsBoost.small <- data.frame(predictionBoost.small, temp$classe)
accBoost.small <-sum(resultsBoost.small[,1] == resultsBoost.small[,2])/length(temp$classe)
accBoost.small
## [1] 0.9602244

resultsBoost.smaller <- data.frame(predictionRf.smaller, temp$classe)
accBoost.smaller <-sum(resultsBoost.smaller[,1] == resultsBoost.smaller[,2])/length(temp$classe)
accBoost.smaller
## [1] 0.9928608



##train1.prComp <- prcomp(train1.small)
##plot(train1.prComp$x[,1], train1.prComp$x[,2])
## made plot that loop up and around to the right

## Confusion Matrix
modelFit <- train(training$type ~ ., method = "glm", preProcess="pca", data=training)
confusionMatrix(testing$type, predict(modelFit, testing))


```



### References

Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013.

Read more: http://groupware.les.inf.puc-rio.br/har#ixzz3P78EmOe4

